BusinessManagement/views/geography.py
import pycountry
import json
from flask import Blueprint, request

geo = Blueprint("geo", __name__, url_prefix='/geo')
# TODO DO NOT EDIT
# these are javascript endpoints used from country_state_selector.html
@geo.route("/countries")
def countries():
    # extract just the data we need for our <select> options
    countries = map(lambda c: {"code": c.alpha_2, "name": c.name},list(pycountry.countries))
    return json.dumps(list(countries))

@geo.route("/states")
def states():
    # extract just the data we need for our <select> options
    status = list(map(lambda s: {"name": s.name, "code": s.code.split("-")[1]}, 
        list(pycountry.subdivisions.get(country_code=request.args.get('country_code', 'US')))))
    return json.dumps(status)

BusinessManagement/views/index.py
from flask import Blueprint, render_template
home = Blueprint('home', __name__, url_prefix='/')

# TODO DO NOT EDIT
@home.route('/')
def index():
    return render_template("index.html")

BusinessManagement/templates/add_company.html
{% extends "layout.html" %}
{% block title %}Add Company{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Add Company</div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for
            name
            address
            city
            website
            #}
            {# Generated fields for name, address, city, website - Aaqib Rafiulla, ar2576, Dec 3, 2022 #}
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name"  placeholder="Enter name" name="name">
              </div>
              <div class="form-group">
                <label for="address">Address</label>
                <input type="text" class="form-control" id="address" placeholder="Enter address" name="address">
              </div>
              <div class="form-group">
                <label for="city">City</label>
                <input type="text" class="form-control" id="city" placeholder="Enter city" name="city">
              </div>
              <div class="form-group">
                <label for="zip">Zip</label>
                <input type="text" class="form-control" id="zip" placeholder="Enter zip" name="zip">
              </div>
              <div class="form-group">
                <label for="website">Website</label>
                <input type="text" class="form-control" id="website" placeholder="Enter website" name="website">
              </div>
            {# use this for country/state selection #}
            {% include "country_state_selector.html" %}
            <input type="submit" class="btn btn-primary" value="Save Company" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/add_employee.html
{% extends "layout.html" %}
{% block title %}Add Employee{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Add Employee</div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for
            first_name
            last_name
            email
            #}
            {# Generated fields for first_name, last_name, email to add the employee - Aaqib Rafiulla, ar2576, Dec 3, 2022 #}
            <div class="form-group">
                <label for="first name">First name</label>
                <input type="text" class="form-control" id="first name"  placeholder="Enter first name" name="first_name">
              </div>
              <div class="form-group">
                <label for="last name">Last name</label>
                <input type="text" class="form-control" id="last name"  placeholder="Enter last name" name="last_name">
              </div>
              <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email"  placeholder="Enter email" name="email">
              </div>
            {# use the below for company selection #}
            {% include "company_dropdown.html" %}
            <input type="submit" class="btn btn-primary" value="Save Employee" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/company_dropdown.html
{% set comps = get_companies() %}
{# can set val prior to inclusion to prefill this field #}
{# TODO DO NOT EDIT #}
<select class="form-select" name="company" value="{{val or ''}}">
    <option value="">No Company</option>
    {% for c in comps %}
    {# example of using external data setting and casting #}
    <option {{'selected' if val|string==c['id']|string}} value="{{c['id']}}">{{c['name']}}</option>
    {% endfor %}
</select>

BusinessManagement/templates/country_state_selector.html
{# TODO DO NOT EDIT #}
{% set c = request.args.get("country", request.form.get("country", country or '')) %}
{% set s = request.args.get("state", request.form.get("state", state or '')) %}
{% if layout and layout == 'horizontal' %}
{# version for filter forms #}
<div class="col-12">
    <label class="visually-hidden" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="col-12">
    <label class="visually-hidden" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% else %}
{# version for add/edit forms #}
<div class="form-group mb-3">
    <label class="form-label" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="form-group mb-3">
    <label class="form-label" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% endif %}
<script>
    //gets called on page load and when the country selection changes
    const fetchStates = (country) => {
        //use jinja to return a string in the html template
        //this string will be as if we did let state = "whatever"
        let state = "{{s}}";
        console.log("fetching", country);
        fetch(`{{url_for('geo.states')}}?country_code=${country}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='state']");

                //if we had options, "clear" it to be the default option
                //so appending works
                if (ele.children.length > 1) {
                    ele.innerHTML = `<option value="">Select State...</option>`;
                }
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args state
                ele.value = state;
            });
    }
    window.addEventListener("load", () => {
        //use jinja to return a string in the html template
        //this string will be as if we did let country = "whatever"
        let country = "{{c}}";
        //get the country list from the endpoint
        fetch(`{{url_for('geo.countries')}}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='country']");
                ele.value = "";//clear the value so "onchange" works
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args country
                ele.value = country;
            })
            .finally(() => {
                //get the state list from the endpoint
                fetchStates(country);
            });
    });
</script>

BusinessManagement/templates/edit_company.html
{% extends "layout.html" %}
{% block title %}Edit Company{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Edit Company</div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for
            name
            address
            city
            website
            and prefill the fields with loaded company data
            #}
            {# Generated fields for name, address, city, website to edit company - Aaqib Rafiulla, ar2576, Dec 3, 2022 #}
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name"  placeholder="Enter name" name="name" value="{{row.name}}">
              </div>
              <div class="form-group">
                <label for="address">Address</label>
                <input type="text" class="form-control" id="address" placeholder="Enter address" name="address" value="{{row.address}}">
              </div>
              <div class="form-group">
                <label for="city">City</label>
                <input type="text" class="form-control" id="city" placeholder="Enter city" name="city" value="{{row.city}}">
              </div>
              <div class="form-group">
                <label for="zipcode">Zip</label>
                <input type="text" class="form-control" id="zipcode" placeholder="Enter Zip" name="zip" value="{{row.zip}}">
              </div>
              <div class="form-group">
                <label for="website">Website</label>
                <input type="text" class="form-control" id="website" placeholder="Enter website" name="website" value="{{row.website}}">
              </div>
            {# use this for country/state selection #}
            {% include "country_state_selector.html" %}
            <input type="submit" class="btn btn-primary" value="Save Company" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/edit_employee.html
{% extends "layout.html" %}
{% block title %}Edit Employee{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Edit Employee</div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for
            first_name
            last_name
            email
            and prefill the fields with loaded employee data
            #}
            {# Generated fields for first_name, last_name, email - Aaqib Rafiulla, ar2576, Dec 3, 2022 #}
            <div class="form-group">
                <label for="first name">First name</label>
                <input type="text" class="form-control" id="first name"  placeholder="Enter first name" name="first_name" value="{{row.first_name}}">
              </div>
              <div class="form-group">
                <label for="last name">Last name</label>
                <input type="text" class="form-control" id="last name"  placeholder="Enter last name" name="last_name" value="{{row.last_name}}">
              </div>
              <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email"  placeholder="Enter email" name="email" value="{{row.email}}">
              </div>
            {# use the below for company selection #}
            {% include "company_dropdown.html" %}
            <input type="submit" class="btn btn-primary" value="Save Employee" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/index.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center text-warning">Ducks In a Row</div>
    <div class="w-50 mx-auto bg-light text-center caption border">At Ducks In A Row, we help
        organize your
        companies and
        employees all in one simple dashboard.</div>
    <div class="lead">
        {# Changed my name and ucid and updated my section- Aaqib Rafiulla, ar2576, Nov 28,2022 #} 
        Brought to you by Aaqib Rafiulla (ar2576) from section IS601-007
        {# TODO replace my name with your first name #}
        {# TODO replace my ucid with your ucid #}
        {# TODO replace both with your section (i.e., 005, 007, etc) #}
    </div>
</div>
{% endblock %}

BusinessManagement/templates/layout.html
<!doctype html>
<html>

<head>
    {% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <style>
        .footer {
            display: block;
        }

        .header {
            top: 0;
            height: 60px;
            line-height: 60px;
        }
    </style>
    <title>{% block title %}{% endblock %} - MP2</title>
    {% endblock %}
</head>

<body>
    <div id="header">
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                {# TODO replace my ucid mt85 with your ucid #}
                {# Replaced ucid mt85 with my ucid ar2576 #}
                <a class="navbar-brand" href="{{url_for('home.index')}}">DIAR-ar2576</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {# TODO fill in the relevant hrefs using url_for() #}
                {# Addeed hrefs links- Aaqib Rafiulla, ar2576, Nov 28,2022 #}
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!-- company dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Company
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="/company/search">Search</a></li>
                                <li><a class="dropdown-item" href="/company/add">Add</a></li>

                            </ul>
                        </li>
                        <!-- employee dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Employee
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="/employee/search">Search</a></li>
                                <li><a class="dropdown-item" href="/employee/add">Add</a></li>
                            </ul>
                        </li>
                        <!-- admin dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="/admin/importCSV">Import</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% include 'flash.html' %}
    </div>
    <div id="content" class="overflow-scroll" style="height: 84vh">
        {% block content %} {% endblock %}
    </div>
    <div id=" footer" class="footer mt-auto py-3 bg-light text-center fixed-bottom">
        <div class="container">
            {% block footer %}
            <span>Business Management &copy; Copyright 2022.</span>
            {% endblock %}
        </div>
    </div>
</body>

</html>

BusinessManagement/templates/list_companies.html
{% extends "layout.html" %}
{% block title %}Company Directory{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center">Company Directory</div>
    {# TODO
    build a horizontal filter/sort form with
    name (company name)
    country/state (provided)
    sort/order (using allowed_columns and provided partial template)
    limit
    ensure all fields prefill with request arg data if provided
    #}
    {# Added horizontal filter/sort form with name (company name) country/state (provided) sort/order using allowed_columns and provided partial template - Aaqib Rafiulla,ar2576, Dec 3, 2022 #}
    <form method="GET">
        {% with layout = "horizontal" %}
        <div class="form-group mb-3">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name"  placeholder="Enter name">
          </div>
        {% include "country_state_selector.html" %}
        {% endwith %}
        {% with cols = allowed_list %}
        {% include "sort_filter.html" %}
        {% endwith %}
        <div class="form-group mb-3">
            <label for="limit">Limit</label>
            <input type="text" class="form-control" id="limit" name="limit" placeholder="Set limit">
          </div>
        <div>
        <span class="col-4">
            <input type="submit" class="btn btn-primary" value="Filter" />
        </span>
        <span class="col-4">
            <a href="?" class="btn btn-secondary">Reset</a>
        </span>
    </div>
    </form>
    <div class="table-responsive">
    <table class="table">
        {% if rows and rows|length > 0 %}
        <thead>
            <tr class="text-capitalize">
                {# generate th tags for each column to display #}
                {# IMPORTANT use table column names as the headings, replace _ with space #}
                {# Added th tags for each columns - Aaqib Rafiulla, ar2576, Dec 3, 2022 #}
                <th>Company id</th>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>Country</th>
                <th>State</th>
                <th>Zip</th>
                <th>Website</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {# generate tr with td tags for each piece of data #}
            {# if the td is for website, display it as a link where the text is "website" and the url is the
            website url #}
            {# in the last column add the following
            a view button that passes the company id to employee search (this will be a company employee
            directory) also pass company_name as an argumen
            an edit button that passes the company id to company edit
            a delete button that passes the company id and the request args to the company delete route
            #}
            {# generated tr with td tags for each piece of data- Aaqib Rafiulla, ar2576, Dec 3, 2022 #}
            {%for row in rows%}
                <tr>
                    <td>{{row.id}}</td>
                    <td>{{row.name}}</td>
                    <td>{{row.address}}</td>
                    <td>{{row.city}}</td>
                    <td>{{row.country}}</td>
                    <td>{{row.state}}</td>
                    <td>{{row.zip}}</td>
                    <td><a href={{row.website}}>{{row.website}}</a></td>
                    <td>
                        <a href="/company/search?company_name={{row.name}}" class="btn btn-primary">View</a>
                        <a href="/company/edit?id={{row.id}}" class="btn btn-secondary">Edit</a>
                        <a href="/company/delete?id={{row.id}}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {%endfor%}
        </tbody>
        {% else %}
        <tbody>
            <tr>
                <td colspan="100%">No results to show</td>
            </tr>
        </tbody>
        {% endif %}
    </table>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/list_employees.html
{% extends "layout.html" %}
{% block title %}Employee Directory{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center">{{request.args.get("company_name","")}} Employee Directory</div>
    <form method="GET">
        {# TODO
        build a horizontal filter/sort form with
        first_name
        last_name
        email
        company (provided)
        sort/order (using allowed_columns and provided partial template)
        limit
        ensure all fields prefill with request arg data if provided
        #}
        {# Added horizontal filter/sort form with name (company name) country/state (provided) sort/order using allowed_columns and provided partial template - Aaqib Rafiulla,ar2576, Dec 3, 2022 #}
        <div class="form-group mb-3">
            <label for="first_name">First name</label>
            <input type="text" class="form-control" id="first_name" name="first_name"  placeholder="Enter first name">
          </div>
          <div class="form-group mb-3">
            <label for="last_name">Last name</label>
            <input type="text" class="form-control" id="last_name" name="last_name"  placeholder="Enter last name">
          </div>
          <div class="form-group mb-3">
            <label for="email">Email</label>
            <input type="text" class="form-control" id="email" name="email"  placeholder="Enter email">
          </div>
        <div class="col-12">
            <label class="visually-hidden" for="company">Company</label>
            {% with val = request.args.get("company_name", '') %}
            {% include "company_dropdown.html" %}
            {% endwith %}
        </div>
        {% with cols = allowed_list %}
        {% include "sort_filter.html" %}
        {% endwith %}
        <div class="form-group mb-3">
            <label for="limit">Limit</label>
            <input type="text" class="form-control" id="limit" name="limit" placeholder="Set limit">
          </div>
        <span class="col-4">
            <input type="submit" class="btn btn-primary" value="Filter" />
        </span>
        <span class="col-4">
            <a href="?" class="btn btn-secondary">Reset</a>
        </span>
    </form>
    <table class="table">
        {% if rows and rows|length > 0 %}
        <thead>
            <tr class="text-capitalize">
                {# generate th tags for each column to display #}
                {# IMPORTANT use table column names as the headings, replace _ with space #}
                {# Added th tags for each columns - Aaqib Rafiulla, ar2576, Dec 3, 2022 #}
                <th>Employee id</th>
                <th>First name</th>
                <th>Last name</th>
                <th>email</th>
                <th>Company Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {# generate tr with td tags for each piece of data #}
            {# in the last column add the following
            an edit button that passes the employee id to employee edit
            a delete button that passes the employee id and the request args to the employee delete route
            #}
            {# generated tr with td tags for each piece of data - Aaqib Rafiulla, ar2576, Dec 3, 2022 #}
            {%for row in rows%}
                <tr>
                    <td>{{row.id}}</td>
                    <td>{{row.first_name}}</td>
                    <td>{{row.last_name}}</td>
                    <td>{{row.email}}</td>
                    <td>{{row.company_name}}</td>
                    <td>
                        <a href="/employee/edit?id={{row.id}}" class="btn btn-secondary">Edit</a>
                        <a href="/employee/delete?id={{row.id}}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {%endfor%}
        </tbody>
        {% else %}
        <tbody>
            <tr>
                <td colspan="100%">No results to show</td>
            </tr>
        </tbody>
        {% endif %}
    </table>
</div>
{% endblock %}

BusinessManagement/templates/sort_filter.html
{# TODO DO NOT EDIT #}
<div class="col-12">
    <label class="visually-hidden" for="col">Field</label>
    <select class="form-select" id="col" name="column" value="{{request.args.get('column', '')}}">
        <option value="">Field...</option>
        {% for v,l in cols %}
        <option {{'selected' if v==request.args.get('column', '' )}} value="{{v}}">{{l}}</option>
        {% endfor %}
    </select>
</div>
<div class="col-12">
    <label class="visually-hidden" for="order">Order</label>
    <select class="form-select" id="order" name="order" value="{{request.args.get('order', 'asc')}}">
        <option {{'selected' if request.args.get('order')=='asc' }} value="asc">Up</option>
        <option {{'selected' if request.args.get('order')=='desc' }} value="desc">Down</option>
    </select>
</div>

BusinessManagement/templates/upload.html
{% extends "layout.html" %}
{% block title %}Import Data{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Import Data</div>
    <div>
        <form method="POST" enctype="multipart/form-data">
            <div class="form-group mb-3">
                <label class="form-label" for="n">Search File</label>
                <input class="form-control" id="n" name="file" type="file" />
            </div>
            <input type="submit" class="btn btn-primary" value="Import" />
        </form>
    </div>
</div>
{% endblock %}